### ISSUE TITLE
Playbooks - Multi-Level Parameters 

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#1829]
e.g.
```
params:
  - name: namespace
     type: config
        filter:
            types: 
                 - Kubernetes::Namespace
        
  - name: rolebinding
     type: config
        filter:
            labelSelector:  namespace=$(.params.namespace.name)              
            types: 
                 - Kubernetes::RoleBinding
```
