### ISSUE TITLE
Playbook params - Config params 

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#2108]
```yaml
config:
   types:
       - EC2::Instance
     
params:
- name: Volume
   type: config-cascade
   properties:
        config:  # name of the config param to cascade from or if unspecifed the config selected for the playbook to run as 
        itemsPath: "$..block_device_mappings[*]"
        namePath: "$.DeviceName"
        valuePath: "$.Ebs.VolumeId"         
 ```
