### ISSUE TITLE
Agent Installation - Use external secret

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#2404]
i.e. 

```
  values:
    upstream:
         createSecret: false
         secretName: upstream
 ```
---
apiVersion: v1
kind: Secret
metadata:
  name: upstream
stringData:
  UPSTREAM_HOST: ""
  UPSTREAM_USER: token
  UPSTREAM_PASSWORD: ""
  AGENT_NAME: "YOUR_LOCAL_NAME"
```

instead of:

```
  values:
    upstream.createSecret: true
    upstream.host: 
    upstream.username: token
    upstream.password: 
    upstream.agentName: 
```
